# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# For previewing drafts run jekyll with --drafts
# 'bundle exec jekyll serve --drafts'
#
# For live reloading add -l
#
# To get the path of a gem enter "bundle info [gem name] --path"

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Christophers thoughts
author: Christopher Astfalk
email: christopher.astfalk@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  My blog, where I post not often.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://christopher-astfalk.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: terreii
github_username:  Terreii
linkedin_username: christopher-astfalk
rss: RSS-Feed

show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives

# Pages in the header
header_pages:
  - index.md
  - portfolio.md
  - title: usePouchDB
    url: /use-pouchdb
  - impressum.md

minima:
  date_format: "%Y-%m-%d"

# Collections of posts
# Tags and year for now
# jekyll-archives:
#   enabled:
#     - tags
#     - year
#   layouts:
#     tag: tag-archive
#     year: year-archive
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tag/:name/'
#     category: '/category/:name/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
